/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 14.07.2026 11:05:43

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[3] = { -1746, 2733, -644, };
const TfArray<1, int> tensor_dimension6 = { 1, { 3 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00013685532030649483, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[3*400] = { 
  -35, 12, 11, 47, -30, -16, 7, -28, 30, 32, 35, 114, 47, -40, 4, 46, -17, -14, -16, 45, -41, 6, -8, -3, 18, 11, 49, 66, 34, -23, -15, 17, -12, 14, -10, 10, -17, -18, -32, -7, 24, -7, -8, 54, 1, -21, 44, -2, 8, -25, -17, 11, -25, -12, 2, -3, -7, -8, 18, 25, 6, 9, 52, -11, 13, 0, -2, 36, -51, 2, -12, -3, 1, 13, 12, 30, -15, -19, 54, 30, -59, -6, -4, 45, -33, -25, 6, -2, 25, 29, 22, 26, 4, -32, 27, 26, -44, 5, 5, 46, -36, 14, -9, -7, 50, 10, 27, -7, 12, -1, -31, 34, -6, 19, 7, 26, -30, -2, -15, 22, 45, 16, 24, 14, 11, -5, 6, 24, -11, -5, -17, 36, 16, -16, 2, -20, 40, 4, 29, 19, 14, -10, -16, 27, -7, 18, -6, 29, -40, 5, -8, -19, 22, 1, 16, 31, 24, -14, 7, 21, -12, -12, -12, 31, -10, 0, -4, -7, 24, 14, 17, 42, 25, 8, 13, 6, 6, -1, 12, 17, 16, -12, -12, -5, 19, 9, -2, -1, -14, -9, 4, 3, 0, 14, -3, 23, -24, -4, 12, 10, 4, 34, 14, -11, 17, -4, 34, 4, -28, 4, 2, 45, 1, -8, -37, -6, 52, 27, 24, -7, 20, -20, -20, 35, -18, 10, 5, 19, -13, -4, -9, 0, 44, 35, 6, 8, 31, 8, -26, 23, -27, 38, 3, 21, 5, -4, -26, 11, 36, 30, 32, 46, 38, 8, -18, 39, -2, -17, 21, 25, -21, -12, -8, -4, 13, 16, 13, 44, 25, -22, 7, 28, -6, 6, -10, 13, -25, -7, -20, -17, 24, -6, -1, 25, 15, 13, -18, 22, -36, 25, 4, -11, -33, -14, -37, 19, 17, 13, 13, 1, 14, 3, 3, 29, -64, 18, 3, 9, -24, 10, -2, 13, 5, 35, 16, -48, 18, -1, -45, 35, -12, 9, 16, 21, 7, 10, -36, 9, 35, 20, 31, -44, -16, -11, -29, 17, -18, 16, -16, -3, -3, 20, -41, 3, 11, 8, 13, 9, 42, -9, -51, 9, 4, 42, 2, -4, 3, -1, -35, 19, 28, 24, 37, 38, 21, -26, -27, 42, -5, 26, 17, 18, 24, 22, -18, 3, 41, 44, 37, 42, 13, -6, -41, 50, -43, -2, -6, -3, 18, -12, -13, -15, 23, 31, 22, 12, 12, -73, -72, 40, 
  52, 5, 10, -18, 37, 12, 38, -13, -12, -1, 11, -55, -20, 11, -15, -14, 11, 13, -16, -12, 71, -25, 49, -28, -1, -26, 8, -50, -33, -60, -8, -29, -11, -7, -37, 4, 69, -28, 62, -3, -20, -11, 31, -23, 13, -19, -35, 9, -36, 22, -12, 7, 66, -7, 30, -11, 15, 22, 21, -44, 2, -49, -102, 26, -40, 10, -11, 14, 85, -25, 60, -20, 22, 5, 14, -8, -3, -59, -127, -4, 0, -9, -7, -11, 76, -8, 32, -12, 11, -2, 18, -9, 0, 50, -34, -4, 8, -37, 14, 2, 39, -17, 33, -3, -17, -19, -17, 12, -35, -3, 19, -9, -17, -43, -20, -6, 54, -10, 45, -40, -29, -15, 10, -6, -12, -50, -37, -38, -4, -4, -26, 12, 6, -24, 38, -10, -26, -19, 11, 16, -6, 4, 13, -11, -11, -9, -1, 1, 53, -16, 52, -16, -10, -18, -8, -18, -15, -4, 18, -13, -8, 17, 0, 12, 17, -22, 42, -14, -30, -14, -10, -15, 11, -12, -3, 4, -22, -12, -21, 27, 12, -23, 48, -40, -9, 15, 28, -11, -20, -42, -58, 33, 4, -10, -27, 13, 79, -14, 30, -16, 6, -11, 33, 2, -11, -7, -42, 16, 37, -49, -10, -6, 28, -12, 41, 4, -42, -19, -8, -10, -30, 19, 41, -11, 27, -16, 1, 23, 32, -1, 45, -30, -27, -29, 6, -5, -26, -14, 22, -45, 26, -38, -24, 8, 29, -9, 55, -15, -54, -58, -26, -27, -46, 11, 11, -45, 24, -2, -32, 0, 17, -33, 46, -11, -23, -10, 11, -15, -42, -1, -17, -18, 4, -23, -29, 9, 39, -46, 57, -44, -26, -1, 19, -52, -4, -18, 15, -22, 4, -36, -22, 25, 20, -34, 59, -45, -4, -19, 13, -33, -28, -56, -20, -12, -1, 3, -34, 13, 22, -22, 41, -13, -3, -15, 1, 21, -42, -45, -5, 4, -22, -33, -26, 30, 0, -30, 61, 4, -12, -19, -25, 12, 7, -14, 26, -18, -49, -13, 21, 39, -10, -33, 86, 7, 0, -12, 5, 3, -45, -40, 34, -32, -48, -40, -17, 48, 24, -20, 74, -44, -41, -23, -16, -27, -21, -37, 37, -19, -28, -20, -13, 51, -26, -34, 39, -21, -20, -22, -39, -13, -31, -24, 44, -26, -34, 2, -28, 64, -9, -36, 50, -12, -6, 4, 23, -29, 12, -28, 31, -7, 
  -13, -15, 6, -72, -26, 1, -65, 15, -32, -30, -48, -95, -42, 28, 12, -36, 9, -2, 23, -24, -33, 27, -23, 9, -52, 6, -53, -46, -26, 42, 29, -13, 15, -7, 26, -31, -34, 20, -72, 33, -18, -10, -31, -58, -2, 23, -13, -23, 21, 2, 13, -44, -43, -1, -75, 19, -6, -26, -41, -20, -3, 16, 7, -28, 28, 15, 10, -50, -34, 13, -63, 15, -61, -20, -58, -19, 23, 64, 26, -53, 32, 2, 30, -68, -36, 16, -57, 13, -46, -11, -88, -33, -5, 14, -4, -41, 14, 14, -4, -35, -21, 16, -58, 15, -29, -19, -43, -9, 1, 1, 0, -12, 3, 14, 26, -48, -16, 26, -35, 13, -13, -19, -51, -61, -27, 27, 20, -30, 18, 11, 21, -56, -12, 13, -47, 14, -33, -12, -73, -54, 8, 1, 17, -40, 2, -9, 15, -13, -4, 5, -28, 7, -35, 19, -5, -43, -23, 1, -14, -17, 33, 5, 3, -25, -7, 21, -26, 11, -7, -10, -28, -24, -32, -16, -12, -8, 13, -10, 23, -35, -40, 17, -45, 42, -23, -19, -26, 3, 18, 36, 53, -37, 15, -2, 16, -44, -38, 18, -78, 34, -14, -22, -47, 13, -3, -3, -1, -23, -10, 10, 1, -43, -33, 13, -33, -6, -5, -8, -30, 20, 7, 11, -12, -22, -28, 9, 4, -25, -27, 1, -31, 2, 8, -18, -3, 19, -22, 1, -7, 12, 2, 18, -7, -29, -28, 2, -39, 0, 3, 14, -6, -7, 13, -20, -6, -7, -17, 18, 3, -13, -17, 26, -75, 26, -14, 12, -40, -26, -2, -4, 8, -15, -4, 15, 33, -38, -16, 26, -45, 15, -20, 6, -20, -10, -18, -5, -16, 1, 17, 7, 15, -40, -22, 9, -43, 29, -23, -33, -29, 5, -1, 49, -1, -7, 56, -33, 10, -30, -6, 16, -59, 5, 3, -19, -46, 24, -2, 28, 36, -43, 32, 21, 2, -54, -3, 9, -31, 8, -21, -4, -30, 15, 26, 12, 6, 8, 45, -8, 1, -35, -4, -5, -51, 17, -15, -25, -25, -5, -7, 25, 34, 16, 19, -19, 16, -69, -4, 21, -64, 11, -14, -26, -39, -36, -1, 48, -13, -23, 20, 1, 14, -85, -2, 11, -47, 22, -24, -31, -42, -16, -19, 40, 12, -36, 42, 7, 20, -82, -50, 9, -61, 1, -41, -36, -77, -10, -7, 65, 48, -47, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 3,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0088090728968381882, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -4083, -608, -4038, 879, 6821, -2404, 5513, -2169, -266, -243, 1937, -522, -835, -2935, -2690, -585, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 6.0403937823139131e-05, 4.1958428482757881e-05, 4.5814103941665962e-05, 7.0791706093586981e-05, 5.4838903452036902e-05, 6.2094251916278154e-05, 6.2398379668593407e-05, 5.85150919505395e-05, 4.6701465180376545e-05, 5.1196941058151424e-05, 3.7144058296689764e-05, 5.026962753618136e-05, 3.9442078559659421e-05, 5.3289462812244892e-05, 5.2845105528831482e-05, 3.8684527680743486e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ -104,51,70,2,42,18,3,5, -127,-6,64,7,24,36,26,0, -93,37,73,16,1,15,22,6, 
  /* [1][0][][] */ -65,15,-91,90,-6,-20,-18,-12, -32,4,-127,33,43,75,28,84, -22,-39,-100,-43,-7,-21,-2,-28, 
  /* [2][0][][] */ -98,12,-19,3,118,13,10,19, -98,-21,29,34,127,-3,7,49, -99,24,23,-6,92,37,41,-11, 
  /* [3][0][][] */ 127,-55,-26,20,-21,-22,-22,22, 114,-75,-48,75,-42,-27,-12,-3, 71,-49,-42,26,-31,-17,21,16, 
  /* [4][0][][] */ -5,-56,-41,-53,-52,-82,2,-25, -69,-54,-25,-33,-89,-32,4,-66, -35,-23,96,-6,-127,-13,-18,-51, 
  /* [5][0][][] */ -106,22,8,24,77,10,-10,43, -100,16,-27,-5,93,69,-26,-7, -127,38,23,18,79,47,-19,21, 
  /* [6][0][][] */ 104,-19,-21,-21,-52,-49,8,-54, 127,-51,-14,-12,-37,-48,2,-31, 75,-72,-39,10,-31,-40,-21,-81, 
  /* [7][0][][] */ -95,32,-21,-13,37,79,36,25, -98,22,31,32,127,68,21,22, -99,-23,-15,9,112,52,34,21, 
  /* [8][0][][] */ -61,-88,-80,68,-60,-25,40,41, -88,-103,-127,65,-44,-40,-43,76, -81,-83,-78,72,-64,1,-9,-39, 
  /* [9][0][][] */ -29,-47,-62,71,-50,10,32,49, -54,-77,-107,0,-43,2,-15,-3, -68,-61,-127,37,-44,3,-13,52, 
  /* [10][0][][] */ -47,-95,-107,96,-66,-49,27,-14, -88,-125,-83,24,-121,-71,-37,2, -62,-79,-92,113,-127,0,-7,80, 
  /* [11][0][][] */ -88,-9,-28,101,-12,-44,-18,-41, -102,-59,6,66,-13,-77,-3,38, -82,-55,12,127,-66,-70,-39,-33, 
  /* [12][0][][] */ -82,-38,-62,127,-13,-24,46,-15, -87,-38,-104,1,-53,25,-36,-61, -70,-14,-5,16,25,-54,-34,75, 
  /* [13][0][][] */ -96,-12,10,6,61,127,-23,-1, -102,56,8,9,35,54,-14,-4, -90,17,102,13,120,89,-30,19, 
  /* [14][0][][] */ -1,2,65,8,55,27,1,10, -9,49,127,9,64,11,17,-12, 98,-93,73,17,87,-11,-4,-6, 
  /* [15][0][][] */ -73,-68,-111,87,-74,-45,-33,60, -104,-127,-87,88,-95,-53,-4,34, -85,-123,-63,96,-119,-19,8,30, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0081977974623441696, 0.0056944414973258972, 0.0062177195213735104, 0.0096075860783457756, 0.0074425316415727139, 0.0084272008389234543, 0.0084684751927852631, 0.0079414499923586845, 0.0063381488434970379, 0.0069482582621276379, 0.0050410530529916286, 0.0068224063143134117, 0.0053529320284724236, 0.0072322473861277103, 0.007171940989792347, 0.0052501200698316097, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 4076, -8821, 4901, 9531, 5213, -1335, -6388, 6527, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 7.06287901266478e-05, 1.8543920305091888e-05, 2.2635298591922037e-05, 3.1364612368633971e-05, 2.5025252398336306e-05, 1.9945731764892116e-05, 7.5379834925115574e-06, 1.7017229765770026e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ -6,-24,-37,-18,-27,-6,-1,7,2,1,-20,-19,-27,-50,-38,10,23,-47,-13,8,-38,-37,-81,-60,-11,-2,37,-6,-44,-94,-85,-91,-63,-28,0,-8,5,10,19,6, -7,-17,-36,1,-7,-24,5,12,3,5,-16,4,-17,-16,-24,-9,11,-55,-27,16,-49,-49,-78,-83,-43,-5,36,3,-21,-78,-98,-95,-74,-34,-8,0,8,18,5,-1, -3,-8,-19,-15,-1,-19,-25,-8,-8,-1,-17,-20,-13,-52,-40,-19,8,-65,-13,6,-61,-70,-86,-84,-53,-15,22,5,-53,-107,-121,-127,-98,-39,-22,-20,8,28,24,1, 
  /* [1][0][][] */ -119,-81,-118,-64,-65,24,-116,-5,-72,68,97,28,32,40,77,39,-11,51,26,80,86,-74,-21,-11,-12,-32,-71,-28,-39,6,-6,-13,-7,-9,24,58,18,-14,14,34, -39,4,-88,-39,-38,41,-52,4,-54,56,79,26,18,35,-5,52,30,31,-44,26,87,-14,-62,-36,-66,-17,-37,-38,-32,26,-25,24,1,11,13,22,24,6,6,21, -71,-78,-115,-127,-85,14,-48,-33,-95,78,67,66,35,42,27,29,15,93,19,24,42,-46,-83,-11,-5,30,-63,27,-47,-45,10,6,17,-76,1,52,60,6,-26,75, 
  /* [2][0][][] */ 52,127,-28,-31,-11,-41,-58,-70,-91,-54,-1,-69,7,2,-40,32,53,13,19,-4,62,-16,-54,7,58,-47,-73,-50,-68,-70,-71,-1,-28,42,70,9,57,-2,29,9, 50,88,12,-36,22,-3,-56,-101,-47,-74,26,-68,-26,40,20,43,12,28,9,16,40,15,-58,7,30,18,-59,-13,-97,-64,-61,20,-25,34,33,17,-2,32,-3,6, 51,62,-16,-12,27,-23,-41,-60,-60,-69,-42,-55,-11,50,-10,38,11,11,36,-37,53,-2,-78,10,81,-49,-45,-45,-63,-12,-23,-20,-2,-10,56,5,24,37,0,-6, 
  /* [3][0][][] */ -58,-68,25,4,-56,-116,-6,-85,-23,-32,-13,-64,-23,39,13,-9,16,-36,-14,44,-31,64,43,28,6,77,-21,-66,-13,-2,8,84,75,-10,20,23,-39,-47,-84,-15, -63,-74,20,10,-79,-100,-1,-86,-8,-14,-27,-46,-30,11,29,-32,19,-16,-28,57,-33,44,26,40,-5,32,-30,-60,-25,-32,10,97,66,-25,-23,-20,-50,-74,-50,-83, -51,-81,30,11,-90,-127,-15,-35,-100,-13,11,-88,-18,22,-23,1,7,-33,-32,61,-68,59,18,28,-27,41,-23,-30,-1,-38,12,56,49,-37,-26,-11,-26,-56,-81,-69, 
  /* [4][0][][] */ -7,-24,5,28,-21,-4,-29,13,2,15,-34,20,47,119,65,94,-65,-40,-96,-90,-36,-55,-34,7,-34,-1,-1,7,14,4,-12,12,-36,-29,16,-5,11,35,4,24, -40,-30,19,-29,-36,-18,-3,-32,-12,-1,-23,7,28,125,49,57,-64,-9,-78,-90,-25,-12,6,30,-20,36,0,-33,-21,29,-30,24,-48,-56,19,28,1,9,-19,6, -41,-66,-40,-12,-46,-27,-24,-19,-29,-1,-17,27,59,127,35,69,-70,-37,-81,-66,-18,-30,-14,-10,-18,-22,-22,-14,-26,28,17,-36,8,-20,-18,32,39,21,6,-29, 
  /* [5][0][][] */ 9,62,49,-12,10,13,-57,-40,-74,-15,-85,0,-7,-39,-80,-32,-7,77,92,81,-105,-64,-58,-112,-49,-82,-28,26,-46,42,-52,-18,-7,-3,3,-7,-17,-30,23,-20, -12,-4,60,-13,-7,-6,-56,-73,-93,-72,-94,-66,-23,-60,-104,-39,21,53,127,83,-77,-84,-76,-61,-83,-42,-59,42,-2,23,-26,-58,-47,23,-52,-20,2,30,-15,-30, 32,-1,91,-37,-11,9,-34,-52,-60,-28,-40,-25,-41,-50,-110,-12,46,55,94,5,-84,-34,-115,-61,-52,-77,4,38,-3,0,-3,-21,-28,-37,-48,-40,-14,-37,13,39, 
  /* [6][0][][] */ 48,97,-42,17,-25,-49,-80,-84,-85,-118,-83,-16,-66,-69,-12,-39,-61,68,-1,-33,-57,33,-24,14,-63,-26,78,-5,13,-58,-20,-116,29,-106,-63,55,-127,69,-42,-38, -67,-76,40,12,-43,104,59,58,37,30,-43,69,-94,28,68,-46,-50,-99,63,63,-62,-122,-40,-43,-116,77,-43,29,-54,-53,60,53,-106,50,-89,69,89,51,-89,-52, -27,-50,-97,-42,-103,-94,-37,-49,71,62,-118,-108,-32,-98,-87,-95,65,-96,14,-52,-33,-125,38,-33,-4,-34,-125,-32,-48,35,-76,-42,-41,51,-35,86,-58,-105,-117,3, 
  /* [7][0][][] */ 35,-42,99,-44,84,5,-25,-84,-119,27,80,-23,-55,-71,-29,65,-25,52,-67,-13,35,45,23,14,-9,-39,-89,-22,-31,9,-25,-23,59,66,50,29,36,-34,-22,-67, -45,29,127,-34,34,-15,61,-66,-98,92,83,-8,-60,-32,-45,34,-56,-7,-44,-40,44,47,98,51,-38,-37,-102,-31,-46,-43,-51,-3,65,43,97,71,26,1,-52,-42, 30,-46,82,-48,17,8,38,-89,-104,76,41,43,-122,-11,5,85,-5,40,-14,-3,51,70,106,74,-67,33,-60,-19,-73,9,16,45,0,15,14,81,-14,-38,-10,-30, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.018080970272421837, 0.0047472435981035233, 0.0057946364395320415, 0.0080293407663702965, 0.0064064646139740944, 0.0051061073318123817, 0.0019297237740829587, 0.0043564108200371265, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.0073683131486177444, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.01553572341799736, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,3 } };
const TfArray<1, float> quant21_scale = { 1, { 0.3893854022026062, } };
const TfArray<1, int> quant21_zero = { 1, { 9 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1049740_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1049740_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1049740_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1049740_4_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1049740_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
